from datetime import datetime, timedelta, timezone


AVISO_MVP = (
    "Este sistema e um MVP academico. As informacoes sao simuladas e nao "
    "substituem avaliacao medica profissional."
)

BAIRROS = [
    "Centro",
    "Zona 01",
    "Zona 02",
    "Zona 03",
    "Zona 04",
    "Zona 05",
    "Zona 06",
    "Zona 07",
    "Zona 08",
    "Jardim Alvorada",
    "Maringa Velho",
    "Mandacaru",
    "Morangueira",
    "Jardim Iguacu",
    "Jardim Universo",
    "Jardim Olimpico",
    "Vila Operaria",
    "Jardim Pinheiros",
    "Conjunto Requiao",
    "Jardim Internorte",
    "Jardim Ceu Azul",
    "Jardim Paraiso",
]

ESPECIALIDADES = [
    "Clinico Geral",
    "Enfermagem",
    "Pediatria",
    "Ginecologia",
    "Obstetricia",
    "Cardiologia",
    "Endocrinologia",
    "Ortopedia",
    "Psicologia",
    "Psiquiatria",
    "Odontologia",
    "Dermatologia",
    "Neurologia",
    "Oftalmologia",
    "Otorrinolaringologia",
    "Vacinacao",
    "Urgencia",
    "Emergencia",
]

STATUS_VALIDOS = [
    "Aguardando",
    "Chamado",
    "Em atendimento",
    "Finalizado",
    "Cancelado",
    "Encaminhado",
]


def agora_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def data_relativa_iso(dias: int = 0, minutos: int = 0) -> str:
    data = datetime.now(timezone.utc) - timedelta(days=dias, minutes=minutos)
    return data.replace(microsecond=0).isoformat()


usuarios = [
    {
        "id": 1,
        "nome": "Paciente Demo",
        "email": "paciente@vittas.com.br",
        "senha": "123456",
        "perfil": "paciente",
        "pacienteId": 1,
    },
    {
        "id": 2,
        "nome": "Funcionario UBS",
        "email": "funcionario@vittas.com.br",
        "senha": "123456",
        "perfil": "funcionario",
    },
    {
        "id": 3,
        "nome": "Admin VITTAS",
        "email": "admin@vittas.com.br",
        "senha": "123456",
        "perfil": "admin",
    },
    {
        "id": 4,
        "nome": "Dra. Camila Fernandes",
        "email": "profissional@vittas.com.br",
        "senha": "123456",
        "perfil": "profissional",
        "profissionalId": 1,
    },
]

profissionais = [
    {
        "id": 1,
        "nome": "Dra. Camila Fernandes",
        "registro": "CRM-PR 12345",
        "especialidade": "Clinico Geral",
        "unidadeId": 11,
    }
]

pacientes = [
    {
        "id": 1,
        "nome": "Maria Oliveira",
        "cpf": "111.222.333-44",
        "dataNascimento": "1992-04-10",
        "idade": 34,
        "telefone": "(44) 99999-1001",
        "email": "maria.oliveira@exemplo.com",
        "bairro": "Centro",
        "endereco": "Rua Santos Dumont, 120",
        "cartaoSus": "700000000000001",
        "historicoMedico": "Sem historico relevante informado.",
        "alergias": "Nenhuma conhecida",
        "medicamentosUsoContinuo": "Nenhum",
        "contatoEmergencia": "Jose Oliveira - (44) 99999-2001",
        "ultimoCheckin": data_relativa_iso(minutos=72),
        "historicoAtendimentos": [],
    },
    {
        "id": 2,
        "nome": "Joao Santos",
        "cpf": "222.333.444-55",
        "dataNascimento": "1959-08-22",
        "idade": 67,
        "telefone": "(44) 99999-1002",
        "email": "joao.santos@exemplo.com",
        "bairro": "Jardim Alvorada",
        "endereco": "Avenida Alvorada, 450",
        "cartaoSus": "700000000000002",
        "historicoMedico": "Hipertensao controlada.",
        "alergias": "Dipirona",
        "medicamentosUsoContinuo": "Losartana",
        "contatoEmergencia": "Ana Santos - (44) 99999-2002",
        "ultimoCheckin": data_relativa_iso(minutos=58),
        "historicoAtendimentos": [],
    },
    {
        "id": 3,
        "nome": "Ana Souza",
        "cpf": "333.444.555-66",
        "dataNascimento": "1998-02-18",
        "idade": 28,
        "telefone": "(44) 99999-1003",
        "email": "ana.souza@exemplo.com",
        "bairro": "Zona 07",
        "endereco": "Rua Bernardino de Campos, 300",
        "cartaoSus": "700000000000003",
        "historicoMedico": "Rinite alergica.",
        "alergias": "Poeira",
        "medicamentosUsoContinuo": "Nenhum",
        "contatoEmergencia": "Marcos Souza - (44) 99999-2003",
        "ultimoCheckin": data_relativa_iso(minutos=50),
        "historicoAtendimentos": [],
    },
    {
        "id": 4,
        "nome": "Pedro Lima",
        "cpf": "444.555.666-77",
        "dataNascimento": "2018-11-02",
        "idade": 8,
        "telefone": "(44) 99999-1004",
        "email": "responsavel.pedro@exemplo.com",
        "bairro": "Mandacaru",
        "endereco": "Avenida Mandacaru, 800",
        "cartaoSus": "700000000000004",
        "historicoMedico": "Asma leve.",
        "alergias": "Nenhuma conhecida",
        "medicamentosUsoContinuo": "Broncodilatador conforme orientacao medica",
        "contatoEmergencia": "Patricia Lima - (44) 99999-2004",
        "ultimoCheckin": data_relativa_iso(minutos=44),
        "historicoAtendimentos": [],
    },
    {
        "id": 5,
        "nome": "Carlos Mendes",
        "cpf": "555.666.777-88",
        "dataNascimento": "1981-06-12",
        "idade": 45,
        "telefone": "(44) 99999-1005",
        "email": "carlos.mendes@exemplo.com",
        "bairro": "Morangueira",
        "endereco": "Avenida Lucilio de Held, 90",
        "cartaoSus": "700000000000005",
        "historicoMedico": "Sem historico relevante informado.",
        "alergias": "Nenhuma conhecida",
        "medicamentosUsoContinuo": "Nenhum",
        "contatoEmergencia": "Paula Mendes - (44) 99999-2005",
        "ultimoCheckin": data_relativa_iso(minutos=36),
        "historicoAtendimentos": [],
    },
    {
        "id": 6,
        "nome": "Helena Rocha",
        "cpf": "666.777.888-99",
        "dataNascimento": "1954-01-03",
        "idade": 72,
        "telefone": "(44) 99999-1006",
        "email": "helena.rocha@exemplo.com",
        "bairro": "Maringa Velho",
        "endereco": "Rua Vitor Meireles, 250",
        "cartaoSus": "700000000000006",
        "historicoMedico": "Diabetes tipo 2.",
        "alergias": "Nenhuma conhecida",
        "medicamentosUsoContinuo": "Metformina",
        "contatoEmergencia": "Roberto Rocha - (44) 99999-2006",
        "ultimoCheckin": data_relativa_iso(minutos=31),
        "historicoAtendimentos": [],
    },
    {
        "id": 7,
        "nome": "Fernanda Costa",
        "cpf": "777.888.999-00",
        "dataNascimento": "1995-09-14",
        "idade": 31,
        "telefone": "(44) 99999-1007",
        "email": "fernanda.costa@exemplo.com",
        "bairro": "Zona 08",
        "endereco": "Avenida Guedner, 1800",
        "cartaoSus": "700000000000007",
        "historicoMedico": "Sem historico relevante informado.",
        "alergias": "Nenhuma conhecida",
        "medicamentosUsoContinuo": "Nenhum",
        "contatoEmergencia": "Bruno Costa - (44) 99999-2007",
        "ultimoCheckin": data_relativa_iso(minutos=20),
        "historicoAtendimentos": [],
    },
    {
        "id": 8,
        "nome": "Lucas Pereira",
        "cpf": "888.999.000-11",
        "dataNascimento": "2007-03-30",
        "idade": 19,
        "telefone": "(44) 99999-1008",
        "email": "lucas.pereira@exemplo.com",
        "bairro": "Jardim Iguacu",
        "endereco": "Avenida Nildo Ribeiro da Rocha, 5400",
        "cartaoSus": "700000000000008",
        "historicoMedico": "Sem historico relevante informado.",
        "alergias": "Nenhuma conhecida",
        "medicamentosUsoContinuo": "Nenhum",
        "contatoEmergencia": "Renata Pereira - (44) 99999-2008",
        "ultimoCheckin": data_relativa_iso(minutos=15),
        "historicoAtendimentos": [],
    },
]

unidades = [
    {
        "id": 1,
        "nome": "UBS Aclimacao",
        "tipo": "UBS",
        "bairro": "Zona 08",
        "endereco": "Avenida Guedner, 1630",
        "tempoMedio": 15,
        "especialidades": ["Clinico Geral", "Enfermagem", "Odontologia", "Vacinacao"],
        "fila": [],
    },
    {
        "id": 2,
        "nome": "UBS Alvorada I",
        "tipo": "UBS",
        "bairro": "Jardim Alvorada",
        "endereco": "Avenida Doutor Alexandre Rasgulaeff, 498",
        "tempoMedio": 15,
        "especialidades": ["Clinico Geral", "Enfermagem", "Pediatria", "Vacinacao"],
        "fila": [],
    },
    {
        "id": 3,
        "nome": "UBS Alvorada III",
        "tipo": "UBS",
        "bairro": "Jardim Alvorada",
        "endereco": "Rua Pioneiro Alfredo Jose da Costa, 567",
        "tempoMedio": 15,
        "especialidades": ["Clinico Geral", "Enfermagem", "Ginecologia", "Vacinacao"],
        "fila": [],
    },
    {
        "id": 4,
        "nome": "UBS Ceu Azul",
        "tipo": "UBS",
        "bairro": "Jardim Ceu Azul",
        "endereco": "Rua Antonio Miles, s/n",
        "tempoMedio": 15,
        "especialidades": ["Clinico Geral", "Enfermagem", "Pediatria"],
        "fila": [],
    },
    {
        "id": 5,
        "nome": "UBS Iguacu",
        "tipo": "UBS",
        "bairro": "Jardim Iguacu",
        "endereco": "Avenida Nildo Ribeiro da Rocha, 5328",
        "tempoMedio": 15,
        "especialidades": ["Clinico Geral", "Enfermagem", "Vacinacao"],
        "fila": [],
    },
    {
        "id": 6,
        "nome": "UBS Mandacaru",
        "tipo": "UBS",
        "bairro": "Mandacaru",
        "endereco": "Avenida Mandacaru, 465",
        "tempoMedio": 15,
        "especialidades": ["Clinico Geral", "Enfermagem", "Odontologia"],
        "fila": [],
    },
    {
        "id": 7,
        "nome": "UBS Maringa Velho",
        "tipo": "UBS",
        "bairro": "Maringa Velho",
        "endereco": "Rua Vitor Meireles, 192",
        "tempoMedio": 15,
        "especialidades": ["Clinico Geral", "Enfermagem", "Psicologia"],
        "fila": [],
    },
    {
        "id": 8,
        "nome": "UBS Morangueira",
        "tipo": "UBS",
        "bairro": "Morangueira",
        "endereco": "Avenida Lucilio de Held, 44",
        "tempoMedio": 15,
        "especialidades": ["Clinico Geral", "Enfermagem", "Vacinacao"],
        "fila": [],
    },
    {
        "id": 9,
        "nome": "UBS Pinheiros",
        "tipo": "UBS",
        "bairro": "Jardim Pinheiros",
        "endereco": "Rua Valeriana, 282",
        "tempoMedio": 15,
        "especialidades": ["Clinico Geral", "Enfermagem", "Pediatria"],
        "fila": [],
    },
    {
        "id": 10,
        "nome": "UBS Zona 07",
        "tipo": "UBS",
        "bairro": "Zona 07",
        "endereco": "Rua Bernardino de Campos, 119",
        "tempoMedio": 15,
        "especialidades": ["Clinico Geral", "Enfermagem", "Odontologia"],
        "fila": [],
    },
    {
        "id": 11,
        "nome": "UPA Zona Norte",
        "tipo": "UPA",
        "bairro": "Jardim Alvorada",
        "endereco": "Avenida Dona Sophia Rasgulaeff, 1053",
        "tempoMedio": 10,
        "especialidades": ["Urgencia", "Emergencia", "Clinico Geral", "Enfermagem"],
        "fila": [],
    },
    {
        "id": 12,
        "nome": "UPA Zona Sul",
        "tipo": "UPA",
        "bairro": "Jardim Higienopolis",
        "endereco": "Avenida Nildo Ribeiro da Rocha, 865",
        "tempoMedio": 10,
        "especialidades": ["Urgencia", "Emergencia", "Clinico Geral", "Enfermagem"],
        "fila": [],
    },
    {
        "id": 13,
        "nome": "Hospital Municipal de Maringa Dra. Thelma Villanova Kasprowicz",
        "tipo": "Hospital",
        "bairro": "Jardim Ipanema",
        "endereco": "Avenida Arquiteto Nildo Ribeiro da Rocha, 865",
        "tempoMedio": 10,
        "especialidades": ["Urgencia", "Emergencia", "Internacao", "Clinico Geral"],
        "fila": [],
    },
]

triagens = [
    {
        "id": 1,
        "pacienteId": 1,
        "sintomas": ["Consulta de rotina"],
        "inicioSintomas": "Sem sintomas agudos",
        "verificouFebre": False,
        "faltaArIntensa": False,
        "desmaio": False,
        "convulsao": False,
        "sangramentoIntenso": False,
        "acidenteGrave": False,
        "suspeitaAvc": False,
        "gestante": False,
        "crianca": False,
        "idoso": False,
        "especialidadeDesejada": "Clinico Geral",
        "classificacao": "Baixa prioridade",
        "scorePrioridade": 10,
        "unidadeRecomendadaId": 1,
        "especialidadeRecomendada": "Clinico Geral",
        "alertaEmergencia": False,
        "mensagemAlerta": None,
        "dataHora": data_relativa_iso(minutos=72),
    },
    {
        "id": 2,
        "pacienteId": 2,
        "sintomas": ["Febre", "Tosse"],
        "inicioSintomas": "Ha 4 dias",
        "verificouFebre": True,
        "faltaArIntensa": False,
        "desmaio": False,
        "convulsao": False,
        "sangramentoIntenso": False,
        "acidenteGrave": False,
        "suspeitaAvc": False,
        "gestante": False,
        "crianca": False,
        "idoso": True,
        "especialidadeDesejada": "Clinico Geral",
        "classificacao": "Alta prioridade",
        "scorePrioridade": 90,
        "unidadeRecomendadaId": 11,
        "especialidadeRecomendada": "Clinico Geral",
        "alertaEmergencia": False,
        "mensagemAlerta": None,
        "dataHora": data_relativa_iso(minutos=58),
    },
    {
        "id": 3,
        "pacienteId": 3,
        "sintomas": ["Dor de cabeca", "Nausea ou vomito"],
        "inicioSintomas": "Desde ontem",
        "verificouFebre": False,
        "faltaArIntensa": False,
        "desmaio": False,
        "convulsao": False,
        "sangramentoIntenso": False,
        "acidenteGrave": False,
        "suspeitaAvc": False,
        "gestante": False,
        "crianca": False,
        "idoso": False,
        "especialidadeDesejada": "Clinico Geral",
        "classificacao": "Media prioridade",
        "scorePrioridade": 40,
        "unidadeRecomendadaId": 10,
        "especialidadeRecomendada": "Clinico Geral",
        "alertaEmergencia": False,
        "mensagemAlerta": None,
        "dataHora": data_relativa_iso(minutos=50),
    },
    {
        "id": 4,
        "pacienteId": 4,
        "sintomas": ["Febre", "Tosse"],
        "inicioSintomas": "Ha 3 dias",
        "verificouFebre": True,
        "faltaArIntensa": False,
        "desmaio": False,
        "convulsao": False,
        "sangramentoIntenso": False,
        "acidenteGrave": False,
        "suspeitaAvc": False,
        "gestante": False,
        "crianca": True,
        "idoso": False,
        "especialidadeDesejada": "Pediatria",
        "classificacao": "Alta prioridade",
        "scorePrioridade": 85,
        "unidadeRecomendadaId": 11,
        "especialidadeRecomendada": "Pediatria",
        "alertaEmergencia": False,
        "mensagemAlerta": None,
        "dataHora": data_relativa_iso(minutos=44),
    },
    {
        "id": 5,
        "pacienteId": 5,
        "sintomas": ["Dor abdominal"],
        "inicioSintomas": "Ha 2 dias",
        "verificouFebre": False,
        "faltaArIntensa": False,
        "desmaio": False,
        "convulsao": False,
        "sangramentoIntenso": False,
        "acidenteGrave": False,
        "suspeitaAvc": False,
        "gestante": False,
        "crianca": False,
        "idoso": False,
        "especialidadeDesejada": "Clinico Geral",
        "classificacao": "Media prioridade",
        "scorePrioridade": 40,
        "unidadeRecomendadaId": 8,
        "especialidadeRecomendada": "Clinico Geral",
        "alertaEmergencia": False,
        "mensagemAlerta": None,
        "dataHora": data_relativa_iso(minutos=36),
    },
    {
        "id": 6,
        "pacienteId": 6,
        "sintomas": ["Retorno"],
        "inicioSintomas": "Acompanhamento",
        "verificouFebre": False,
        "faltaArIntensa": False,
        "desmaio": False,
        "convulsao": False,
        "sangramentoIntenso": False,
        "acidenteGrave": False,
        "suspeitaAvc": False,
        "gestante": False,
        "crianca": False,
        "idoso": True,
        "especialidadeDesejada": "Psicologia",
        "classificacao": "Alta prioridade",
        "scorePrioridade": 90,
        "unidadeRecomendadaId": 7,
        "especialidadeRecomendada": "Psicologia",
        "alertaEmergencia": False,
        "mensagemAlerta": None,
        "dataHora": data_relativa_iso(minutos=31),
    },
    {
        "id": 7,
        "pacienteId": 7,
        "sintomas": ["Vacinacao"],
        "inicioSintomas": "Nao se aplica",
        "verificouFebre": False,
        "faltaArIntensa": False,
        "desmaio": False,
        "convulsao": False,
        "sangramentoIntenso": False,
        "acidenteGrave": False,
        "suspeitaAvc": False,
        "gestante": False,
        "crianca": False,
        "idoso": False,
        "especialidadeDesejada": "Vacinacao",
        "classificacao": "Baixa prioridade",
        "scorePrioridade": 10,
        "unidadeRecomendadaId": 1,
        "especialidadeRecomendada": "Vacinacao",
        "alertaEmergencia": False,
        "mensagemAlerta": None,
        "dataHora": data_relativa_iso(minutos=20),
    },
    {
        "id": 8,
        "pacienteId": 8,
        "sintomas": ["Retorno"],
        "inicioSintomas": "Acompanhamento",
        "verificouFebre": False,
        "faltaArIntensa": False,
        "desmaio": False,
        "convulsao": False,
        "sangramentoIntenso": False,
        "acidenteGrave": False,
        "suspeitaAvc": False,
        "gestante": False,
        "crianca": False,
        "idoso": False,
        "especialidadeDesejada": "Clinico Geral",
        "classificacao": "Baixa prioridade",
        "scorePrioridade": 10,
        "unidadeRecomendadaId": 5,
        "especialidadeRecomendada": "Clinico Geral",
        "alertaEmergencia": False,
        "mensagemAlerta": None,
        "dataHora": data_relativa_iso(minutos=15),
    },
    {
        "id": 9,
        "pacienteId": 1,
        "sintomas": ["Falta de ar"],
        "inicioSintomas": "Ha algumas horas",
        "verificouFebre": False,
        "faltaArIntensa": True,
        "desmaio": False,
        "convulsao": False,
        "sangramentoIntenso": False,
        "acidenteGrave": False,
        "suspeitaAvc": False,
        "gestante": False,
        "crianca": False,
        "idoso": False,
        "especialidadeDesejada": "Emergencia",
        "classificacao": "Emergencia",
        "scorePrioridade": 130,
        "unidadeRecomendadaId": 13,
        "especialidadeRecomendada": "Emergencia",
        "alertaEmergencia": True,
        "mensagemAlerta": "Em sinais graves, ligue 192 ou procure atendimento imediato.",
        "dataHora": data_relativa_iso(dias=1, minutos=80),
    },
    {
        "id": 10,
        "pacienteId": 2,
        "sintomas": ["Febre", "Dor abdominal"],
        "inicioSintomas": "Ha 5 dias",
        "verificouFebre": True,
        "faltaArIntensa": False,
        "desmaio": False,
        "convulsao": False,
        "sangramentoIntenso": False,
        "acidenteGrave": False,
        "suspeitaAvc": False,
        "gestante": False,
        "crianca": False,
        "idoso": True,
        "especialidadeDesejada": "Clinico Geral",
        "classificacao": "Alta prioridade",
        "scorePrioridade": 90,
        "unidadeRecomendadaId": 11,
        "especialidadeRecomendada": "Clinico Geral",
        "alertaEmergencia": False,
        "mensagemAlerta": None,
        "dataHora": data_relativa_iso(dias=2, minutos=35),
    },
]

atendimentos = [
    {
        "id": 1,
        "pacienteId": 1,
        "unidadeId": 1,
        "triagemId": 1,
        "status": "Aguardando",
        "posicaoFila": 1,
        "tempoEstimado": 15,
        "dataCheckin": data_relativa_iso(minutos=72),
        "dataInicio": None,
        "dataFinalizacao": None,
        "profissionalId": None,
        "resultado": None,
        "orientacao": None,
        "medicacao": None,
        "intervaloMedicacao": None,
        "dataRetorno": None,
        "scorePrioridade": 10,
        "atestadoDigital": None,
    },
    {
        "id": 2,
        "pacienteId": 2,
        "unidadeId": 11,
        "triagemId": 2,
        "status": "Aguardando",
        "posicaoFila": 1,
        "tempoEstimado": 10,
        "dataCheckin": data_relativa_iso(minutos=58),
        "dataInicio": None,
        "dataFinalizacao": None,
        "profissionalId": None,
        "resultado": None,
        "orientacao": None,
        "medicacao": None,
        "intervaloMedicacao": None,
        "dataRetorno": None,
        "scorePrioridade": 90,
        "atestadoDigital": None,
    },
    {
        "id": 3,
        "pacienteId": 3,
        "unidadeId": 10,
        "triagemId": 3,
        "status": "Chamado",
        "posicaoFila": 1,
        "tempoEstimado": 15,
        "dataCheckin": data_relativa_iso(minutos=50),
        "dataInicio": None,
        "dataFinalizacao": None,
        "profissionalId": None,
        "resultado": None,
        "orientacao": None,
        "medicacao": None,
        "intervaloMedicacao": None,
        "dataRetorno": None,
        "scorePrioridade": 40,
        "atestadoDigital": None,
    },
    {
        "id": 4,
        "pacienteId": 4,
        "unidadeId": 11,
        "triagemId": 4,
        "status": "Aguardando",
        "posicaoFila": 2,
        "tempoEstimado": 20,
        "dataCheckin": data_relativa_iso(minutos=44),
        "dataInicio": None,
        "dataFinalizacao": None,
        "profissionalId": None,
        "resultado": None,
        "orientacao": None,
        "medicacao": None,
        "intervaloMedicacao": None,
        "dataRetorno": None,
        "scorePrioridade": 85,
        "atestadoDigital": None,
    },
    {
        "id": 5,
        "pacienteId": 5,
        "unidadeId": 8,
        "triagemId": 5,
        "status": "Aguardando",
        "posicaoFila": 1,
        "tempoEstimado": 15,
        "dataCheckin": data_relativa_iso(minutos=36),
        "dataInicio": None,
        "dataFinalizacao": None,
        "profissionalId": None,
        "resultado": None,
        "orientacao": None,
        "medicacao": None,
        "intervaloMedicacao": None,
        "dataRetorno": None,
        "scorePrioridade": 40,
        "atestadoDigital": None,
    },
    {
        "id": 6,
        "pacienteId": 6,
        "unidadeId": 7,
        "triagemId": 6,
        "status": "Encaminhado",
        "posicaoFila": 1,
        "tempoEstimado": 10,
        "dataCheckin": data_relativa_iso(minutos=31),
        "dataInicio": data_relativa_iso(minutos=20),
        "dataFinalizacao": None,
        "profissionalId": 1,
        "resultado": None,
        "orientacao": None,
        "medicacao": None,
        "intervaloMedicacao": None,
        "dataRetorno": None,
        "scorePrioridade": 90,
        "atestadoDigital": None,
    },
    {
        "id": 7,
        "pacienteId": 7,
        "unidadeId": 1,
        "triagemId": 7,
        "status": "Aguardando",
        "posicaoFila": 2,
        "tempoEstimado": 30,
        "dataCheckin": data_relativa_iso(minutos=20),
        "dataInicio": None,
        "dataFinalizacao": None,
        "profissionalId": None,
        "resultado": None,
        "orientacao": None,
        "medicacao": None,
        "intervaloMedicacao": None,
        "dataRetorno": None,
        "scorePrioridade": 10,
        "atestadoDigital": None,
    },
    {
        "id": 8,
        "pacienteId": 8,
        "unidadeId": 5,
        "triagemId": 8,
        "status": "Aguardando",
        "posicaoFila": 1,
        "tempoEstimado": 15,
        "dataCheckin": data_relativa_iso(minutos=15),
        "dataInicio": None,
        "dataFinalizacao": None,
        "profissionalId": None,
        "resultado": None,
        "orientacao": None,
        "medicacao": None,
        "intervaloMedicacao": None,
        "dataRetorno": None,
        "scorePrioridade": 10,
        "atestadoDigital": None,
    },
    {
        "id": 9,
        "pacienteId": 1,
        "unidadeId": 13,
        "triagemId": 9,
        "status": "Finalizado",
        "posicaoFila": None,
        "tempoEstimado": 10,
        "dataCheckin": data_relativa_iso(dias=1, minutos=80),
        "dataInicio": data_relativa_iso(dias=1, minutos=70),
        "dataFinalizacao": data_relativa_iso(dias=1, minutos=45),
        "profissionalId": 1,
        "resultado": "Paciente avaliada e orientada no fluxo de urgencia.",
        "orientacao": "Manter acompanhamento conforme orientacao recebida no atendimento.",
        "medicacao": None,
        "intervaloMedicacao": None,
        "dataRetorno": "2026-06-15",
        "scorePrioridade": 130,
        "atestadoDigital": None,
    },
    {
        "id": 10,
        "pacienteId": 2,
        "unidadeId": 11,
        "triagemId": 10,
        "status": "Finalizado",
        "posicaoFila": None,
        "tempoEstimado": 10,
        "dataCheckin": data_relativa_iso(dias=2, minutos=35),
        "dataInicio": data_relativa_iso(dias=2, minutos=25),
        "dataFinalizacao": data_relativa_iso(dias=2, minutos=5),
        "profissionalId": 1,
        "resultado": "Atendimento registrado pelo profissional de saude.",
        "orientacao": "Repouso e retorno se houver piora dos sintomas.",
        "medicacao": "Medicacao registrada manualmente pelo profissional.",
        "intervaloMedicacao": "Conforme prescricao profissional registrada",
        "dataRetorno": "2026-06-20",
        "scorePrioridade": 90,
        "atestadoDigital": {
            "paciente": "Joao Santos",
            "cpf": "222.333.444-55",
            "dataAtendimento": data_relativa_iso(dias=2, minutos=5),
            "unidade": "UPA Zona Norte",
            "profissional": "Dra. Camila Fernandes",
            "cidObservacao": "Campo simulado para demonstracao",
            "diasAfastamento": 2,
            "orientacao": "Repouso e retorno se houver piora dos sintomas.",
            "aviso": "Este documento e uma simulacao academica para demonstracao do MVP VITTAS.",
        },
    },
]

pacientes[0]["historicoAtendimentos"].append(
    {
        "atendimentoId": 9,
        "data": atendimentos[8]["dataFinalizacao"],
        "unidade": "Hospital Municipal de Maringa Dra. Thelma Villanova Kasprowicz",
        "classificacao": "Emergencia",
        "orientacao": atendimentos[8]["orientacao"],
        "medicacao": atendimentos[8]["medicacao"],
        "intervaloMedicacao": atendimentos[8]["intervaloMedicacao"],
        "atestadoDigital": None,
    }
)

pacientes[1]["historicoAtendimentos"].append(
    {
        "atendimentoId": 10,
        "data": atendimentos[9]["dataFinalizacao"],
        "unidade": "UPA Zona Norte",
        "classificacao": "Alta prioridade",
        "orientacao": atendimentos[9]["orientacao"],
        "medicacao": atendimentos[9]["medicacao"],
        "intervaloMedicacao": atendimentos[9]["intervaloMedicacao"],
        "atestadoDigital": atendimentos[9]["atestadoDigital"],
    }
)


def proximo_id(colecao: list[dict]) -> int:
    if not colecao:
        return 1
    return max(item["id"] for item in colecao) + 1
